### ISSUE TITLE
Error when compilng RoiPoolingLayer

### ISSUE THREAD

**Issue by tzrtzr000** [danfeiX/scene-graph-TF-release#12]
Hi I have tried both ways to compile the  RoiPooingLayer. the first one has following error :

> python -c 'import tensorflow as tf; tf.load_o
p_library("PARENT_DIR/scene-graph-TF-release-master/lib/roi_pooling_layer/roi_pooling_op_gpu_cuda8.so")'
Traceback (most recent call last):
  File "\<string\>", line 1, in <module>
  File "TENSORFLOW_PATH/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: TENSORFLOW_PATH/scene-graph-TF-release-master/lib/roi_pooling_layer/roi_pooling_op_gpu_cuda8.so: undefined symbol: _ZN10tensorflow11TensorShapeC1Ev

There are similar problems in TFFRCNN issue post(https://github.com/CharlesShang/TFFRCNN/issues/2).
The solution for it is to add `-D_GLIBCXX_USE_CXX11_ABI=0` g++ compile flag in make.sh, whereas in this version there is no make.sh. Then I tried to add this extra flag on sefl by myself. Then following error appears:

> nvcc -std=c++11 -c -o roi_pooling_op_gpu.cu.o
 roi_pooling_op_gpu.cu.cc -I     $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
roi_pooling_op_gpu.cu.cc:9:57: fatal error: tensorflow/core/user_ops/roi_pooling_op_gpu.h: No such file or directory
Note that I MANUALLY created `.../user_ops/` and move every file under `.../src/ `to `.../user_ops/`. since there is no such folder before and maybe this is the problem. 

Please help me out!  Thanks !!!

**Comment by tzrtzr000** [comment]
Problem solved by using Tensorflow r0.11

**Comment by nicholasmireles** [comment]
I have the same issue ("fatal error: tensorflow/core/user_ops/roi_pooling_op_gpu.h: No such file or directory") and it persists after I installed the correct version of tensorflow.
