### ISSUE TITLE
(v). Use the script provided by py-faster-rcnn to generate (4).

### ISSUE THREAD

**Issue by yanxp** [danfeiX/scene-graph-TF-release#13]
Hello,how to generate RPN. What is it's format?

**Comment by mrliudq** [comment]
And, which script? How many object classes? Any pre-trained model?
Thanks very much~

**Comment by ZhpeWarren** [comment]
@danfeiX   it is also a problem for me.

**Comment by danfeiX** [comment]
Take a look at the provided RPN file. You'll just have to fill all the fields in the .h5 file. Here is the script to generate RPN using py-faster-rcnn https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/rpn_generate.py
