### ISSUE TITLE
How to get the roi proposals

### ISSUE THREAD

**Issue by panfengli** [danfeiX/scene-graph-TF-release#18]
For data preparation, it says that use the script provided by `py-faster-rcnn` to generate (4). RoI proposals: `proposals.h5`. I am wondering whether it should be `fast-rcnn`, since `py-faster-rcnn` doesn't need roi outside proposals.

**Comment by danfeiX** [comment]
https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/rpn_generate.py

**Comment by panfengli** [comment]
@danfeiX I saw here [how to generate region proposals with RPN](https://github.com/rbgirshick/py-faster-rcnn/issues/489), they used

`./tools/rpn_generate.py --gpu 0 --def models/pascal_voc/VGG16/faster_rcnn_alt_opt/rpn_test.pt --net data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel --imdb dataset`

Here `create_imdb.sh` creates an hdf5 file but not imdb file used by Caffe, I am wondering how did you handle this issue. Thanks!
