### ISSUE TITLE
mini-vg dataset link and link to other datasets seem to be broken

### ISSUE THREAD

**Issue by navidre** [danfeiX/scene-graph-TF-release#25]

**Comment by medhini** [comment]
Having the same issue.

**Comment by zhydong** [comment]
#me too

**Comment by danfeiX** [comment]
Looks like this is due to cvgl.stanford.edu being redirected to our new website svl.stanford.edu. I'll try to fix it ASAP.

**Comment by danfeiX** [comment]
Fixed. Closing the issue.
