### ISSUE TITLE
Extracting output features of the GRU

### ISSUE THREAD

**Issue by chenxistephen** [danfeiX/scene-graph-TF-release#27]
Hi,

I was trying to extract the output of the edge/node GRUs (just the edge_factor/vert_factor before update_inference, at https://github.com/danfeiX/scene-graph-TF-release/blob/4c9e3c6a5cb0e6a241a92dc9b786f74e69ca35c4/lib/networks/models.py#L217 . But when I save and retrieve it, it only returns a feature of 512 dimension, instead of the num_roi/num_rel * 512. Is there anyway in Tensorflow to gather this feature across all the dimensions ?

**Comment by danfeiX** [comment]
It should have features of all roi and rels. Maybe try printing the shape when doing forward pass to make sure it is indeed incorrect shape?
