### ISSUE TITLE
Download link is down.

### ISSUE THREAD

**Issue by Nikko1024** [danfeiX/scene-graph-TF-release#30]
The download link in this page is down is down.
https://github.com/danfeiX/scene-graph-TF-release/blob/master/data_tools/README.md

**Comment by danfeiX** [comment]
There's a power outage in our server cluster. Will be restored soon

**Comment by Nikko1024** [comment]
Thanks a lot for your quick response.


On Oct 25, 2018, at 14:00, danfei <notifications@github.com<mailto:notifications@github.com>> wrote:


There's a power outage in our server cluster. Will be restored soon
