### ISSUE TITLE
Where do you separate Train/Val data?

### ISSUE THREAD

**Issue by CongWeilin** [danfeiX/scene-graph-TF-release#31]
According to the paper, you mentioned 70% data for training and 30% for testing. However, I cannot find you data separation in your code. It seems to me that you are testing using training data. Please clarify if I miss something.

**Comment by danfeiX** [comment]
Split is encoded when creating the dataset at https://github.com/danfeiX/scene-graph-TF-release/blob/master/data_tools/vg_to_roidb.py#L586
