### ISSUE TITLE
Tensor name "vert_rnn/gru_cell/gates/biases" not found in checkpoint files checkpoints/dual_graph_vrd_final_iter2.ckpt

### ISSUE THREAD

**Issue by weibo053** [danfeiX/scene-graph-TF-release#4]
I found the following error when running the quick start. Can you give some suggestion?
=============================
NotFoundError (see above for traceback): Tensor name "vert_rnn/gru_cell/gates/biases" not found in checkpoint files checkpoints/dual_graph_vrd_final_iter2.ckpt
	 [[Node: save/RestoreV2_56 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_56/tensor_names, save/RestoreV2_56/shape_and_slices)]]
	 [[Node: save/RestoreV2_28/_69 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_251_save/RestoreV2_28", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by danfeiX** [comment]
Which tensorflow version are you using? The repo currently supports up to 0.12

**Comment by weibo053** [comment]
Probably this is due to the wrong version then. I use v1.0.0 right now.
