### ISSUE TITLE
When recreating the VG-SGG file, the number of objects and relations is different

### ISSUE THREAD

**Issue by VSJMilewski** [danfeiX/scene-graph-TF-release#50]
Hi All, 

I'm trying to add some data to the VG-SGG file, and I thought the easiest way was to try and recreate the processed data. However, when I do this, the number of objects and relations that are remaining changes. 

I have no clue why this is happening. Should I change some settings? Or is something else happening? 

Thanks for the help and any insight you can give!

**Comment by 386469007** [comment]
Hello, have you solved this problem？

**Comment by VSJMilewski** [comment]
Sorry for the late reply. Yes, I did. 
I was trying with both versions available on the VisualGenome website. Apparently, the files linked in the data folder of this repo are a third version. All data versions create different results. 

I don't know how these differences affect results in models, but at least something to consider.
