### ISSUE TITLE
vg_hdf5.py read data defect

### ISSUE THREAD

**Issue by andyhuang01** [danfeiX/scene-graph-TF-release#6]
scene-graph-TF-release/lib/datasets/vg_hdf5.py

line 31: valid_mask = self.roi_h5['img_to_first_box'][:] > 0 should be
'valid_mask = self.roi_h5['img_to_first_box'][:] >= 0', because the first image has index of 0, and invalid index is actually set to be -1 in 'scene-graph-TF-release/data_tools/vg_to_roidb.py'
270         if im_to_first_obj[i] == obj_counter:
271             im_to_first_obj[i] = -1
272             im_to_last_obj[i] = -1

**Comment by danfeiX** [comment]
Fixed. Thanks for the bug report!
